[libraries]
dog-stats-d = "com.datadoghq:java-dogstatsd-client:4.2.0"

interop-common = "com.projectronin.interop:interop-common:3.4.0"
interop-commonTestDb = "com.projectronin.interop:interop-common-test-db:3.4.0"
interop-kafka = "com.projectronin.interop.publish:interop-kafka:7.4.5"

ktorm-core = "org.ktorm:ktorm-core:3.6.0"
ktorm-support-mysql = "org.ktorm:ktorm-support-mysql:3.6.0"
mockk = "io.mockk:mockk:1.13.4"
mysql-connector-java = "com.mysql:mysql-connector-j:8.0.32"
rider-core = "com.github.database-rider:rider-core:1.36.0"
ronin-kafka = "com.projectronin:ronin-kafka:0.3.0"
ronin-kafka-event-resource = "com.projectronin.contract.event:event-interop-resource-retrieve:1.0.0"
spring-boot-parent = "org.springframework.boot:spring-boot-parent:2.7.5"
testcontainers-mysql = "org.testcontainers:mysql:1.17.6"

[bundles]
test-mysql = ["mysql-connector-java", "testcontainers-mysql"]
