[libraries]
interop-common = "com.projectronin.interop:interop-common:1.0.0"
interop-commonTestDb = "com.projectronin.interop:interop-common-test-db:1.0.0"
ktorm-core = "org.ktorm:ktorm-core:3.4.1"
ktorm-support-mysql = "org.ktorm:ktorm-support-mysql:3.4.1"
mockk = "io.mockk:mockk:1.12.3"
mysql-connector-java = "mysql:mysql-connector-java:8.0.29"
rider-core = "com.github.database-rider:rider-core:1.32.3"
testcontainers-mysql = "org.testcontainers:mysql:1.17.1"

[bundles]
test-mysql = ["mysql-connector-java", "testcontainers-mysql"]
