[libraries]
dog-stats-d = "com.datadoghq:java-dogstatsd-client:4.1.0"
interop-common = "com.projectronin.interop:interop-common:3.1.0"
interop-commonTestDb = "com.projectronin.interop:interop-common-test-db:3.1.0"
ktorm-core = "org.ktorm:ktorm-core:3.5.0"
ktorm-support-mysql = "org.ktorm:ktorm-support-mysql:3.5.0"
mockk = "io.mockk:mockk:1.13.2"
mysql-connector-java = "com.mysql:mysql-connector-j:8.0.31"
rider-core = "com.github.database-rider:rider-core:1.35.0"
spring-boot-parent = "org.springframework.boot:spring-boot-parent:2.7.5"
testcontainers-mysql = "org.testcontainers:mysql:1.17.6"

[bundles]
test-mysql = ["mysql-connector-java", "testcontainers-mysql"]
