[libraries]
dog-stats-d = "com.datadoghq:java-dogstatsd-client:4.1.0"
interop-common = "com.projectronin.interop:interop-common:3.1.0"
interop-commonTestDb = "com.projectronin.interop:interop-common-test-db:3.1.0"
interop-kafka = "com.projectronin.interop.publish:interop-kafka:4.2.5-INT1240-SNAPSHOT"
ktorm-core = "org.ktorm:ktorm-core:3.5.0"
ktorm-support-mysql = "org.ktorm:ktorm-support-mysql:3.5.0"
mockk = "io.mockk:mockk:1.13.2"
mysql-connector-java = "com.mysql:mysql-connector-j:8.0.31"
rider-core = "com.github.database-rider:rider-core:1.35.0"
ronin-kafka = "com.projectronin:ronin-kafka:0.0.1-SNAPSHOT"
ronin-kafka-event-resource = "com.projectronin.contract.event:event-interop-patient-retrieve:1.0.0-SNAPSHOT"
spring-boot-parent = "org.springframework.boot:spring-boot-parent:2.7.5"
testcontainers-mysql = "org.testcontainers:mysql:1.17.5"

[bundles]
test-mysql = ["mysql-connector-java", "testcontainers-mysql"]
