[libraries]
interop-common = "com.projectronin.interop:interop-common:3.0.0"
interop-commonTestDb = "com.projectronin.interop:interop-common-test-db:3.0.0"
ktorm-core = "org.ktorm:ktorm-core:3.5.0"
ktorm-support-mysql = "org.ktorm:ktorm-support-mysql:3.5.0"
mockk = "io.mockk:mockk:1.12.7"
mysql-connector-java = "mysql:mysql-connector-java:8.0.30"
rider-core = "com.github.database-rider:rider-core:1.34.0"
testcontainers-mysql = "org.testcontainers:mysql:1.17.3"

[bundles]
test-mysql = ["mysql-connector-java", "testcontainers-mysql"]
