name: Build interop-queue-liquibase image, push to Nexus, and sync with ArgoCD

on:
  workflow_run:
    workflows: [ Interop Queue DB Tests ]
    types: [ completed ]
    branches: [ master ]

jobs:
  get-info:
    name: Standard tags
    runs-on: self-hosted
    env:
      base_directory: ./interop-queue-liquibase

    outputs:
      docker_image_tag: ${{ steps.gradle_info.outputs.docker_image_tag }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "zulu"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: "."

      - name: Get tag from Gradle
        id: gradle_info
        run: |
          git fetch --tags --unshallow
          TAG=$(./gradlew currentVersion | awk '{ if(/Project version:/) { print $3; exit } }' | cut -d\- -f1)
          echo ${TAG}
          echo "::set-output name=docker_image_tag::${TAG}"
        working-directory: "."

  image-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Push multiplatform Docker to Nexus
    needs:
      - get-info
    uses: projectronin/github/.github/workflows/image_push_nexus.yml@master
    with:
      base-directory: ./interop-queue-liquibase
      image-tag: ${{ needs.get-info.outputs.docker_image_tag }}
      repo: "interop-queue-liquibase"
    secrets:
      username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
      password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}

  image-push-sha:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Push multiplatform Docker to Nexus
    needs:
      - get-info
      - image-push
    uses: projectronin/github/.github/workflows/image_push_nexus.yml@master
    with:
      base-directory: ./interop-queue-liquibase
      image-tag: ${{ github.sha }}
      repo: "interop-queue-liquibase"
    secrets:
      username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
      password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}

  image-push-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Push multiplatform Docker to Nexus
    needs:
      - get-info
      - image-push
    uses: projectronin/github/.github/workflows/image_push_nexus.yml@master
    with:
      base-directory: ./interop-queue-liquibase
      image-tag: dev
      repo: "interop-queue-liquibase"
    secrets:
      username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
      password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}

  # argocd_dev:
  #   uses: projectronin/github/.github/workflows/argocd_deploy.yml@master
  #   needs: [get-tags, image-push]
  #   with:
  #     environment: dev
  #     repo: interop-proxy-server
  #     image-tag: ${{ env.DOCKER_IMAGE_TAG }}
  #   secrets:
  #     argocd-svc-automation: ${{ secrets.ARGOCD_SVC_AUTOMATION }}
