name: Interop Queue Kafka Tests
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install DataDog CI
        run:
          npm install -g @datadog/datadog-ci
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradlew Test
        run: ./gradlew :interop-queue-kafka:test
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          file: ./interop-queue-kafka/codecov/test/jacocoTestReport.xml
          flags: kafka

      - name: Upload report to DataDog
        if: always() && !cancelled()
        env:
          DD_ENV: ci
          DATADOG_SITE: datadoghq.com
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        run: datadog-ci junit upload --service interop-queue-kafka ./interop-queue-kafka/build/test-results/test
